### ISSUE TITLE
最新 nowa-template-salt 出错 

### ISSUE THREAD

**Issue by sasbsd** [nowa-webpack/nowa-gui#10]
Router.js:47Uncaught TypeError: Cannot read property 'location' of undefined
使用GUI 工具启动项目正在，但是  "nowa server”  进首页出现该错误

**Comment by Jirapo** [comment]
方便提交demo 给我们吗？

**Comment by gbk** [comment]
@fengsx 帮忙看下吧

**Comment by sasbsd** [comment]
gui 直接创建 nowa-template-salt  v2 模板项目，GUI启动 能正常访问，但是使用 npm start/build 调用nowa 相关命令都不正常，

**Comment by Jirapo** [comment]
你好，
我想请问下你之前是否安装过 nowa 的命令行版本？
你目前的gui的版本号是？
操作系统是？
方便的话，可以直接复制你的操作系统环境变量路径吗？
在终端执行npm start 的时候，终端是否报错？

**Comment by Jirapo** [comment]
我们发现了打包之后的文件 会出现这样的问题：
 Cannot read property 'location' of undefined
您是不是也是访问dist文件里面的东西出现这样的问题的呢？
我们会尽快解决的
