### ISSUE TITLE
.bash_profile 覆盖 path

### ISSUE THREAD

**Issue by fyangstudio** [nowa-webpack/nowa-gui#11]
mac ：每次启动会启用 .bash_profile ，之前有配过 .profile 的话 会被重写，导致配过的 path 失效，请先检查下 PATH 。

**Comment by Jirapo** [comment]
嗯是的，我们会尽快解决的

**Comment by Jirapo** [comment]
您可以在官网重新下载mac版本的包，1.7.2版本的，因为这个版本目前没有发布，所以没有更新提示。
