### ISSUE TITLE
从 scaffold.ant.design 读取脚手架模板

### ISSUE THREAD

**Issue by afc163** [nowa-webpack/nowa-gui#14]
http://scaffold.ant.design/list.json

并从 GitHub 仓库直接下载到本地。

**Comment by Jirapo** [comment]
这些模板因为不走npm的管理流程，所以无法成为nowa模板，不具有版本管理的功能，所以新建出来的项目也不会是nowa项目而是ant项目，工具会把它们作为普通项目处理。

**Comment by Jirapo** [comment]
这个description是认真的么？
![image](https://user-images.githubusercontent.com/7804364/27082822-d5250972-5078-11e7-94b5-cdc3cb9edcbe.png)

**Comment by afc163** [comment]
版本的意义可能不大，一般初始化项目都是从最新版开始。这个诉求后面我会尝试给个 PR。

**Comment by Jirapo** [comment]
之所以有更新按钮，是想要把这个模板在本地缓存一份，用户第二次创建的时候不会再去拉模板了。点击更新按钮会更新本地缓存的模板。
您是希望本地不要缓存模板么？

**Comment by afc163** [comment]
完全没关系。。。

**Comment by Jirapo** [comment]
如果您指的是nowa的模板的版本v1, v2, v3的话，其实是对应branch的，有些模板v2确实是比v1新，但不是v2就一定比v1新的关系。比如salt模板，v1和v2 是模板里面一些依赖不同，但是ui是一样的，是同ui但不同的业务逻辑实现。uxcore的v4和v3也是这样的关系。所以才有版本的。

**Comment by afc163** [comment]
👌 感觉像是两个不同的脚手架。

**Comment by Jirapo** [comment]
fixed.
1.8.2版本发布了，这些脚手架都放上去了，不过这个列表貌似一直在增加啊。
