### ISSUE TITLE
mac下控制台没有输出 点击启动 编译提示 Exec start command finished.

### ISSUE THREAD

**Issue by zb188** [nowa-webpack/nowa-gui#16]
mac下控制台没有输出 点击启动 编译提示 Exec start command finished. 启动一瞬间又自己处于停止状态

**Comment by Jirapo** [comment]
你的gui版本是？
你先前是否执行过停止命令？
你是否点击启动的时候速度比较快，变成了双击？

**Comment by zb188** [comment]
gui版 初次安装启动就闪一下立马停止了，没有快速双击，命令行可以正常启动，有日志文件吗？给我位置我去看看

**Comment by Jirapo** [comment]
在设置页面会显示当前工具的版本号的。
如果你是最新版的gui的话，在~/.nowa-gui/mainlogs 里面会有日志，这个是后台日志。
然后你可以ctrl+shift+8 打开控制台，看界面输出，这里是前端输出。
你有钉钉号吗？

**Comment by zb188** [comment]
ding号：bobo87
控制台
start /Users/mac/NowaProject/demo3
 execCommand start /Users/mac/NowaProject/demo3
refresh project

**Comment by Jirapo** [comment]
我发送了请求。
你点击其他项目的启动也是这样吗？
启动命令集中的命令会马上停止吗？

**Comment by Jirapo** [comment]
.npmrc 环境配置的原因
