### ISSUE TITLE
启动和编译失败，提示Exec build command stopped

### ISSUE THREAD

**Issue by WangYang-Rex** [nowa-webpack/nowa-gui#21]
点击启动或者编译，就会提示Exec build command stopped
<img width="922" alt="123" src="https://user-images.githubusercontent.com/7553998/28612648-7c6c4ebe-7222-11e7-93ea-64cb78c18e42.png">

**Comment by Jirapo** [comment]
可以从官网上重新下载进行安装，mac版本目前有这个问题。

**Comment by WangYang-Rex** [comment]
我明明全局安装过nowa和nowa-build等相关插件，提示还未安装
<img width="922" alt="3" src="https://user-images.githubusercontent.com/7553998/28615198-d809ca5a-722a-11e7-8450-7b6b26ae8361.png">

**Comment by WangYang-Rex** [comment]
终端运行nowa build -h是可以看到已经安装了的
<img width="570" alt="4" src="https://user-images.githubusercontent.com/7553998/28615315-3c0a679e-722b-11e7-8fce-ac237103e282.png">

**Comment by Jirapo** [comment]
你看下你的项目中的依赖，是否安装了nowa？
如果你不需要云构建的话，可以删除项目中的所有与nowa相关的依赖
如果你需要云构建的话，请安装nowa和nowa-build

**Comment by Jirapo** [comment]
在1.9.0前的版本中，项目依赖无法卸载干净，所以最好的方式是删除node_modules, 更改 package.json， 重新导入项目。
1.9.0目前还未发布。
