### ISSUE TITLE
v1.9.0 新建nowa项目界面卡住

### ISSUE THREAD

**Issue by WangYang-Rex** [nowa-webpack/nowa-gui#22]
项目其实已经安装完成了，包括依赖，在这个及诶按一直卡着，必须强制退出才行
![image](https://user-images.githubusercontent.com/7553998/28766289-8f0c130a-7601-11e7-9325-cad5733362a2.png)

**Comment by Jirapo** [comment]
重启工具后，这个项目运行正常吗？
哪个模板？
选择了哪个源地址？

**Comment by WangYang-Rex** [comment]
重启后正常，但是必须重启，不然回不去了，界面没有可以点的地方，
![image](https://user-images.githubusercontent.com/7553998/28766641-126a80e6-7603-11e7-9876-168ab1c02b6e.png)
源地址：http://registry.npm.taobao.org

**Comment by WangYang-Rex** [comment]
我的项目都已经跑起来了，这边还卡着....

**Comment by Jirapo** [comment]
如果界面卡死的话，通常是重启的。或者可以ctrl+shift+8，调出控制台，然后ctrl+r 刷新工具。
你可以看看你截图日志中出现的npm log，然后发我。
你有钉钉吗？

**Comment by WangYang-Rex** [comment]
我这边已经重启了，卡不到日志了

**Comment by Jirapo** [comment]
/Users/wy/.npm/_logs/2017-07-3105_55_12_722z-debug.log
是npm的log，不是gui的。
你的第一张截图里面最后一行显示了log的path

**Comment by WangYang-Rex** [comment]
![image](https://user-images.githubusercontent.com/7553998/28773227-492e289a-761b-11e7-9785-a245c1d2b1ae.png)
