### ISSUE TITLE
打点服务

### ISSUE THREAD

**Issue by Jirapo** [nowa-webpack/nowa-gui#23]
https://github.com/nowa-webpack/nowa-gui/blob/35587966fac2d3f5d224800fc853570020dd18ef/src/main/services/requests.js#L50

@gbk 这里需要怎么修改请求？
把url 字段换成一大串的你提供的recode地址？
还是直接简单的request请求发过去就可以了？

**Comment by tommytroylin** [comment]
request 请求就好。。
具体参数和 @gbk 确认一下

**Comment by gbk** [comment]
https://github.com/nowa-webpack/nowa-gui/pull/24/files
