### ISSUE TITLE
创建项目时模板支持搜索/过滤

### ISSUE THREAD

**Issue by micate** [nowa-webpack/nowa-gui#28]
如图：

![default](https://user-images.githubusercontent.com/433481/29803661-16cbee72-8cb0-11e7-9ac0-4a0000ceb76e.png)

随着模板越来越多，想找到合适的模板就越来越困难了，希望支持搜索或者过滤，方便查找。

**Comment by Jirapo** [comment]
嗯，这个其实一直在我们的考虑范围内。

**Comment by tommytroylin** [comment]
@micate added in `1.9.4`
