### ISSUE TITLE
在添加react-native依赖后，项目编译运行报错

### ISSUE THREAD

**Issue by z810276431** [nowa-webpack/nowa-gui#29]
如题
![image](https://user-images.githubusercontent.com/16434735/29952716-c4c19c30-8efd-11e7-929b-d765bc3cc7b3.png)

**Comment by tommytroylin** [comment]
react-native有自己的技术栈。[docs here](http://facebook.github.io/react-native/docs/getting-started.html)
不能通过 nowa 或者 webpack 进行打包
