### ISSUE TITLE
官网上无法下载

### ISSUE THREAD

**Issue by chinaver2002** [nowa-webpack/nowa-gui#35]
https://alixux.org/downloads/nowa-gui.exe 打不开。

**Comment by tommytroylin** [comment]
非常抱歉。这个地址在恢复中。
请暂时从此处下载使用。
https://github.com/nowa-webpack/nowa-gui/releases

**Comment by tommytroylin** [comment]
https://github.com/nowa-webpack/nowa-gui/issues/34#issuecomment-359329827
