### ISSUE TITLE
怎样增加源地址？

### ISSUE THREAD

**Issue by beautycss** [nowa-webpack/nowa-gui#36]
由于本地有npm仓库，需要安装本地仓库里的一些依赖，所以要设置本地的源地址，目前是无法设置的。

尝试在 `/src/renderer/models/setting.js` 和 `/src/main/userConfig.js` 里修改了 registryList ，增加了本地的源地址，然后重新编译，重启项目重启electron，依然是默认的那3个源地址，修改了全局源地址也不生效，反复试了几次都不行。

 `/src/renderer/models/setting.js`
```
...

export default {
  namespace: 'setting',

  state: {
    defaultEditor: getLocalEditor() || SUBLIME,   // 默认编辑器
    editor: {       // 编辑器列表
      [SUBLIME]: getLocalEditorPath(SUBLIME),
      [VSCODE]: getLocalEditorPath(VSCODE),
      [WEBSTORM]: getLocalEditor(WEBSTORM),
    },
    registry: 'http://192.168.10.10:4873',  //全局源地址
    registryList: [
      'http://192.168.10.10:4873',
      'http://registry.npm.taobao.org',
      'http://registry.npmjs.org',
      'http://registry.npm.alibaba-inc.com',
    ],     //所有源地址列表
    lang: getLocalLanguage(), //当前语言
  },

...
```

`/src/main/userConfig.js`
```
...

const registryList = [
  'http://192.168.10.10:4873',
  'http://registry.npm.taobao.org',
  'http://registry.npmjs.org',
  'http://registry.npm.alibaba-inc.com',
];

...
```

**Comment by gbk** [comment]
@Jirapo 可以帮忙看看这个问题吗？不能设置私有源

**Comment by Jirapo** [comment]
在“设置面板“中的“基本设置“中可以配置源地址。

**Comment by Jirapo** [comment]
你重新编译代码之后，要把用户目录下的.nowa-gui下的配置文件的registyList一起修改掉，或者直接删除。
代码修改是用于初始化用户的配置的，由于你的电脑本身存在的旧配置，新启动程序不会去覆盖这份配置，除非你删除了配置，或者是通过设置面板修改配置，推荐使用设置面板。

**Comment by Jirapo** [comment]
另外，源地址返回的数据得是json的数据格式。

**Comment by gbk** [comment]
- 左下角工具设置
![image](https://user-images.githubusercontent.com/865717/37071886-baa384b8-21f9-11e8-8264-cd7f68a1405f.png)
- 输入你的私有源地址提交即可
![image](https://user-images.githubusercontent.com/865717/37071924-e914cef6-21f9-11e8-958a-13e18a8ab962.png)

> 请确保该地址能被访问到且返回 json 数据

**Comment by beautycss** [comment]
@Jirapo 好的，谢谢，找到原因了，源地址要返回那json数据，不然无效。

**Comment by beautycss** [comment]
@gbk  谢谢，好详细。

**Comment by beautycss** [comment]
已解决，修改了用户目录下的 `.nowa-gui/user_config.json` 文件。
