### ISSUE TITLE
nowa deploy 安装报错

### ISSUE THREAD

**Issue by xs-yantoutou** [nowa-webpack/nowa-gui#59]
Installing nowa-deploy ...
✖ Install fail! Error: [nowa-deploy@1.0.1 › @ali/def-pub-client@^2] GET https://registry.npm.taobao.org/@ali%2Fdef-pub-client/%3E%3D2.0.0%20%3C3.0.0 response 405 status
Error: [nowa-deploy@1.0.1 › @ali/def-pub-client@^2] GET https://registry.npm.taobao.org/@ali%2Fdef-pub-client/%3E%3D2.0.0%20%3C3.0.0 response 405 status
    at get (/Users/jonoboru/xushang/.nvm/versions/node/v14.17.6/lib/node_modules/nowa/node_modules/npminstall/lib/get.js:51:17)
    at get.next (<anonymous>)
    at onFulfilled (/Users/jonoboru/xushang/.nvm/versions/node/v14.17.6/lib/node_modules/nowa/node_modules/co/index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by xs-yantoutou** [comment]
> Installing nowa-deploy ...
> ✖ Install fail! Error: [nowa-deploy@1.0.1 › @ali/def-pub-client@^2] GET https://registry.npm.taobao.org/@ali%2Fdef-pub-client/%3E%3D2.0.0%20%3C3.0.0 response 405 status
> Error: [nowa-deploy@1.0.1 › @ali/def-pub-client@^2] GET https://registry.npm.taobao.org/@ali%2Fdef-pub-client/%3E%3D2.0.0%20%3C3.0.0 response 405 status
> at get (/Users/jonoboru/xushang/.nvm/versions/node/v14.17.6/lib/node_modules/nowa/node_modules/npminstall/lib/get.js:51:17)
> at get.next ()
> at onFulfilled (/Users/jonoboru/xushang/.nvm/versions/node/v14.17.6/lib/node_modules/nowa/node_modules/co/index.js:65:19)
> at processTicksAndRejections (internal/process/task_queues.js:95:5)

是在内网环境下下载的

**Comment by gbk** [comment]
```shell
nowa install deploy --registry=https://registry.npm.alibaba-inc.com
```
