### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by kulelikule** [nowa-webpack/nowa-gui#9]
1.在命令集中点击“删除”，希望能够提示“确认是否删除？”，以防错误操作
2.在命令集中新增“重新启动“按钮，现在是要先停止再启动（操作略麻烦）
3.界面四周加上边框或者阴影，全白的底色有时会和页面分不清楚（这点很让我头疼，操作难受）
4.依赖管理中添加“搜索功能”，特别是dev的依赖过多时真心不好查看

以上的建议望采纳，希望nowa越来越好，加油！

**Comment by Jirapo** [comment]
非常感谢您的意见！
1. 可做
2. 命令集的操作对应的是 package.json 的scripts，字段，操作都是一次性的。除非您在命令体里面写入了两个命令，比如 `npm run stop & npm run start`
3. 您用的是windows版本？ mac版本自带阴影。windows版本我会进行界面修改
4. 可做。

非常感谢～

**Comment by kulelikule** [comment]
我这边觉得控制台的界面太窄了，编译报错的时候要去看错误，感觉不是很舒服，能否支持鼠标拖拽界面使界面变大？

**Comment by kulelikule** [comment]
刚又想到一个，就是在安装依赖的时候，能否支持多个依赖一起安装，现在好像只能一个一个安装

**Comment by Jirapo** [comment]
1.安装依赖可以支持多依赖安装
2. 对于控制台界面放大的话，有两种方案
 a. 增加放大按钮，控制台界面会占据右侧全部分
 b.  控制台界面不变，里面增加横向滚动条。
个人期望第二种方案，这个改起来简单。
你之前的issue 已经解决了，可以下载1.7.2的测试版本，
http://alixux.org/downloads/1.7.2/NowaGUI.exe

**Comment by kulelikule** [comment]
已经用上新版本了，非常棒！
继续可优化的问题：点击界面右上方的“关闭“后，不希望直接退出程序，而是隐藏界面（类似杀毒软件或者QQ安全管家那种效果），要再次打开界面只要点击屏幕右下角的小图标即可

**Comment by Jirapo** [comment]
有最小化图标的呀，__

**Comment by kulelikule** [comment]
可能是我没有表述清楚，我是希望点击“**关闭**“按钮之后任务栏中没有最小化的窗口了，但软件还运行着（可参考qq电脑管家），现在点击关闭是直接关掉软件了

**Comment by Jirapo** [comment]
那它怎么退出呢？我么有windows电脑

**Comment by tommytroylin** [comment]
@kulelikule 这个和正常的`关闭`逻辑不太一样吧。。gui本身并不需要像qq或者电脑管家一样常驻后台。。

**Comment by kulelikule** [comment]
@tommytroylin @Jirapo  我是想开启服务后就在后台了，所以没有其他操作就不去唤出界面了，关闭和启动都直接操作右下角的小图标就好了, 如果不太方便实现也没有关系，让它以最小化的形式存在好了，谢谢你们了~

**Comment by tommytroylin** [comment]
@kulelikule 我重新理解下，你的意思类似于`隐藏主界面`，通过操作右下角的图标的右键菜单来调用GUI中的功能？
@Jirapo 调研一下，看看能不能减少系统消耗。如果现在右键菜单能够覆盖绝大部分的操作需求，隐藏界面应该对MacBook Air或者其他偏低配置的机器有性能上的帮助。

**Comment by Jirapo** [comment]
没有右键菜单，只有任务托盘里面的项目操作，kulelikule 提的还是有必要的，因为我发现用户超级容易误操作，虽然可以增加很多pv， ^_^，隐藏了界面，工具还是在跑的。

**Comment by kulelikule** [comment]
谢谢你们！好开心你们能接受我的意见，支持nowagui~棒棒的~~~

**Comment by Jirapo** [comment]
你能使用gui我才高兴呢，如果可以，请帮我们推广，跪谢了
